spring.application.name=service-desk
spring.datasource.url=${SERVICE_DESK_DB_URL:jdbc:postgresql://localhost:5432/service_desk}
spring.datasource.username=${SERVICE_DESK_DB_USERNAME:${USER}}
spring.datasource.password=${SERVICE_DESK_DB_PASSWORD:}
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
