spring.application.name=service-desk
spring.datasource.url=jdbc:postgresql://localhost:5432/service_desk
spring.datasource.username=Dima2
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false